### ISSUE TITLE
Errors now related to PowerWall software 20.49.0

### ISSUE THREAD

**Issue by spitexau** [bshep/pvoutput#1]
Hi There,

There's been an auth requirements change in Powerwall software. Any chance you can update this package, and docker container to include the new PVOutput code and params etc.

https://forum.pvoutput.org/t/integration-service-not-working-for-powerwall-sw-ver-20-49-0/4000/23

Many thanks in advance

**Comment by bshep** [comment]
I'll look at it now, hopefully its easy to fix

**Comment by bshep** [comment]
@spitexau 

I've updated the version of pvoutput to 1.5.5.1, you will need to edit the config file manually to add the new parameters and you should be set, please let me know if there are any issues ( i cant test at home since my brother is the one with the powerwall and I dont have access to his computer at the moment )

**Comment by spitexau** [comment]
Thanks for looking into this. I just gave it a try. Re-downloaded the docker image on the Synology.

Starting up the container it still says.

2021-02-22 22:40:07,040  INFO [main] (Controller.java:109) - *** Starting PVOutput Integration Service v1.5.4.1

Not sure if the change went through. It still fails.

2021-02-22 22:40:13,755 ERROR [Thread-1] (AHttpLogReader.java:453) - <<< [403] {"code":403,"error":"Unable to GET to resource","message":"User does not have adequate access rights"}

Thanks again.

**Comment by bshep** [comment]
> Thanks for looking into this. I just gave it a try. Re-downloaded the docker image on the Synology.
> 
> Starting up the container it still says.
> 
> 2021-02-22 22:40:07,040 INFO [main] (Controller.java:109) - *** Starting PVOutput Integration Service v1.5.4.1
> 
> Not sure if the change went through. It still fails.
> 
> 2021-02-22 22:40:13,755 ERROR [Thread-1] (AHttpLogReader.java:453) - <<< [403] {"code":403,"error":"Unable to GET to resource","message":"User does not have adequate access rights"}
> 
> Thanks again.

Thats very strange, i re-downloaded the image and  mine reads:

```
2021-02-23 20:04:47,414  INFO [main] (Controller.java:108) - 
2021-02-23 20:04:47,417  INFO [main] (Controller.java:109) - *** Starting PVOutput Integration Service v1.5.5.1
2021-02-23 20:04:47,421  INFO [Thread-0] (Controller.java:130) - Install Directory: /usr/src/app
```

which tag are you pulling? it should be set to 'latest'

EDIT: just to be sure i just re-built, re-uploaded the image

@spitexau - any update on this?
